### ISSUE TITLE
Wrong actions in redmine 1.1.1

### ISSUE THREAD

**Issue by morph027** [edtsech/redmine_wiki_permissions#12]
I just installed the new release of Redmine (1.1.1) and encountered the following problem.

The action defined for editing and so on needs to look like this:

http://test/redmine/projects/test/wiki/Wiki/$action

If this (really helpful) plugin is installed, they look like this:

http://test/redmine/wiki/edit?page=Wiki (should be redmine/projects/test/wiki/Wiki/edit) on the start page and

http://test/redmine/wiki/Test/Test/edit (should be redmine/projects/test/wiki/Test/edit) on a subpage

which leeds to 404 errors. Even the "permissions"-button is missing.

**Comment by jgordor** [comment]
Same problem, are you planning updating the plugin?

**Comment by morph027** [comment]
Would be great...As for now, I've just created a new subproject to hide my secret wiki from others...For the moment, this is granular enough for us.
