### ISSUE TITLE
rake issue

### ISSUE THREAD

**Issue by chrisgo** [edtsech/redmine_wiki_permissions#5]
Running this:

rake db:migrate_plugins RAILS_ENV=production

results in:

(in /var/www/redmine-0.9.2)
rake aborted!
Expected /var/www/redmine-0.9.2/app/models/user.rb to define User
# 

Not really a Ruby (nor RoR) guy ... just trying to install this

Thanks,
Chris

**Comment by edtsech** [comment]
I try to fix this and adapt plugin for Redmine 0.9.\* as soon as posible.

**Comment by chrisgo** [comment]
Thanks - not a big deal, the plugin seems to show up on the plugin list (admin section) but I haven't tried to see if it works yet

**Comment by edtsech** [comment]
I fixed thid bug, check please.

**Comment by chrisgo** [comment]
That worked -- thanks much
