### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by dourouc05** [edtsech/redmine_wiki_permissions#8]
Here is the French translation for this plugin: 

fr.yml

<pre>
fr:
  permission_level_0: Ne peut pas voir
  permission_level_1: Lire
  permission_level_2: Lire et écrire
  permission_level_3: Lire, écrire et modifier les permissions
</pre>

**Comment by dourouc05** [comment]
I forgot to say this was for config/locales/fr.yml. The content is about the same for /lang/fr.yml. 

Also, in app/views/wiki/edit_permissions.html.erb, there is still a line that needs to be translatable (77).

**Comment by jsarenik** [comment]
This issue can be closed:

commit 9f15e69f62c9b8a0d119eb102d601849a44c8420
Author: Edward Tsech edtsech@gmail.com
Date:   Tue May 25 19:58:35 2010 +0700

```
Added French localization
```
